### ISSUE TITLE
[Bug]: Crash on pure 1.7.10 forge instance

### ISSUE THREAD

**Issue by Ydrec** [FalsePattern/LagGogglesLegacy#7] opened 2022-06-07 17:56 UTC
### GPU

Intel

### Modpack (Optional)

Only minecraft 1.7.10, forge 1614 LWJGl 2.9.4 with laggoggles-mc1.7.10-4.12.3, falsepatternlib-mc1.7.10-0.6.1, SpongeMixins-1.2.0

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/LagGogglesLegacy/files/8855435/fml-client-latest.log)

### Description

Immediate crash on startup using multimc 0.6.15-3247 with a new instance containing only forge and Laggoogles with dependencies.

Using Oracle Java jre1.8.0_333/bin/javaw.exe

No arguments or memory limits set

**Comment by FalsePattern** [comment] 2022-06-07 17:58
that's strange, the log mentions nothing about a crash

**Comment by Ydrec** [comment] 2022-06-07 18:01
Sorry, i think this is the actual; crash report
[hs_err_pid3572.log](https://github.com/FalsePattern/LagGogglesLegacy/files/8855503/hs_err_pid3572.log)
seems like it gets killed by windows for memory leak

**Comment by FalsePattern** [comment] 2022-06-07 18:04
this is a gpu driver crash, unfortunately i have no idea what could be causing this.

Could you try adding optifine to the instance and see if that fixes it?

**Comment by Ydrec** [comment] 2022-06-07 18:09
[hs_err_pid13004.log](https://github.com/FalsePattern/LagGogglesLegacy/files/8855546/hs_err_pid13004.log)
[fml-client-latest.log](https://github.com/FalsePattern/LagGogglesLegacy/files/8855547/fml-client-latest.log)
Seems to make no difference

**Comment by FalsePattern** [comment] 2022-06-07 18:16
i've looked further into this crash and the dll mentioned in it, the only possible solutions i've found is fully uninstalling and reinstalling the gpu drivers, as this crash happens in completely native code outside of java.

**Comment by Ydrec** [comment] 2022-06-07 19:27
Solution found: Newer java versions no longer support my outdated intel hd 4000 GPU even on latest available drivers, using Java 8 144 version does work on a pure setup. Seems to work fine in game as well. Also seems like using sponge mixins 1.5.0 works fine. 

Still doesn't work in stock GTNH instance, crashes without even dropping crash log.
[fml-client-latest.log](https://github.com/FalsePattern/LagGogglesLegacy/files/8856001/fml-client-latest.log)
Would appreciate if you can provide some help otherwise issue solved

**Comment by FalsePattern** [comment] 2022-06-07 19:29
Try adding [MixingASM](https://github.com/makamys/Mixingasm) to the pack, it usually fixes mixin<>ASM conflicts automatically

**Comment by Ydrec** [comment] 2022-06-07 20:18
Moved to java 8_241 (working with pure instance), added mixingasm, stock modpack works with  it enabled, enabled LagGoggles and falselib. and it still gives same errors

[fml-client-latest_withmixing.log](https://github.com/FalsePattern/LagGogglesLegacy/files/8856238/fml-client-latest_withmixing.log)
[fml-client-latest.log](https://github.com/FalsePattern/LagGogglesLegacy/files/8856243/fml-client-latest.log)

Doesn't seem to change logged errors
Do i need to specify in mixingasm inclusion list a transformer from LagGoggles?

From what i see there is tons of non trusted transformers mixingasm point out, would try removing these mods to find conflicting one

**Comment by Ydrec** [comment] 2022-06-07 21:24
Log from another person,added laggoggles and falselib, same issue
[message.txt](https://github.com/FalsePattern/LagGogglesLegacy/files/8856677/message.txt)

**Comment by FalsePattern** [comment] 2022-06-07 21:29
i read the logs again, this crash is caused by a mixin mod touching classes it shouldn't inside a mixin plugin (more specifically, something loads `cpw.mods.fml.common.eventhandler.EventBus` too early, before LagGoggles can mixin into it).
This bug is unfixable on my side, it needs to be fixed in whatever mod's doing this.

**Comment by Ydrec** [comment] 2022-06-07 21:29
Found the mod causing the issue: BugTorch-1.1.2-GTNH,  currently trying disabling its features in config to pinpoint the problematic one

**Closed as completed by FalsePattern** 2022-06-07 21:29 UTC
Labels: bug

**Comment by FalsePattern** [comment] 2022-06-07 21:30
closed the issue because it went off-topic from the original bug report, which has been resolved
